In [1]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor

import pandas as pd
import numpy as np

df = pd.read_csv("train.csv")
df=df.drop('id',axis=1)
df.head()

cols_1  cols_2 cols_3 cols_4  cols_5 cols_6  cols_7  cols_8    cols_9  \
0      E    10.2  False   True    8.88      X  type_1   17.28   53693.0   
1      D     9.8  False   True     NaN      X  type_0     NaN   16284.0   
2      E     9.0  False    NaN     NaN    NaN     NaN     NaN  148072.0   
3      B    10.2  False   True   10.36      Z  type_2   18.96   24833.0   
4      B     9.8  False   True    9.25      X  type_1     NaN       NaN   

    cols_10  cols_11   cols_12 cols_13 cols_14   True_value  
0  1.428571  -27.828       NaN   False       D  113094.4584  
1       NaN  -34.785  4.088827    True       D  125632.5840  
2  1.428571  -27.828       NaN    True       B   62800.5840  
3  1.428571  -27.828  5.488590   False       A  244714.9320  
4  1.428571  -27.828  4.088827   False     NaN   81647.0424

In [2]:
from sklearn import preprocessing
le = preprocessing. LabelEncoder()

In [3]:
df_cat=df.select_dtypes(include='object')
df_num=df.select_dtypes(include='float64')
cols=list(df_cat.columns)
cols

['cols_1', 'cols_3', 'cols_4', 'cols_6', 'cols_7', 'cols_13', 'cols_14']

In [4]:
for col in cols:
    impute_col = col
    le.fit(df.loc[:, impute_col])
    dict1=dict(zip(le.classes_, le.transform(le.classes_)))
    df[impute_col]=le.transform(df[impute_col])
    df[impute_col]= df[impute_col].map(lambda x: np.nan if x == len(dict1)-1 else x)

In [5]:
# df.head(200)

In [6]:
imputer = IterativeImputer(random_state=100)

In [7]:
for col in cols:
    impute_col = col
    df_train = df.loc[:, [impute_col]]
    imputer.fit(df_train)
    df_imputed=imputer.transform(df_train)
    df_imputed[:,0].round()
    df.loc[:,[impute_col]]=df_imputed[:,0].round()

In [8]:
df.describe()

cols_1       cols_2       cols_3       cols_4       cols_5  \
count  6000.000000  5403.000000  6000.000000  6000.000000  5456.000000   
mean      4.238333     9.177383     0.026667     0.879167     9.014274   
std       2.692905     0.978018     0.161121     0.325961     3.116929   
min       0.000000     2.800000     0.000000     0.000000     0.000000   
25%       1.000000     8.600000     0.000000     1.000000     7.400000   
50%       4.000000     9.400000     0.000000     1.000000     8.510000   
75%       6.000000     9.800000     0.000000     1.000000    10.360000   
max       9.000000    10.600000     1.000000     1.000000    22.940000   

            cols_6       cols_7       cols_8         cols_9      cols_10  \
count  6000.000000  6000.000000  5401.000000    5317.000000  5396.000000   
mean      1.403000     1.270333    18.667121  110613.712432     1.571270   
std       0.956771     0.755876     5.137441   78920.071559     0.360882   
min       0.000000     0.000000     0.000000       2.000000     0.000000   
25%       1.000000     1.000000    16.080000   51898.000000     1.428571   
50%       1.000000     1.000000    18.480000   94557.000000     1.428571   
75%       2.000000     2.000000    21.120000  158836.000000     1.428571   
max       3.000000     7.000000    45.840000  526162.000000     2.857143   

           cols_11      cols_12     cols_13      cols_14     True_value  
count  5421.000000  5378.000000  6000.00000  6000.000000    6000.000000  
mean    -28.026918     4.193186     0.42050     1.558500  100642.231474  
std       4.759328     0.850703     0.49368     1.061963   68357.773577  
min     -34.785000     1.834008     0.00000     0.000000    3769.920000  
25%     -27.828000     4.088827     0.00000     1.000000   56517.384000  
50%     -27.828000     4.088827     0.00000     2.000000   86519.664000  
75%     -27.828000     4.088827     1.00000     2.000000  125632.584000  
max     -13.914000    14.949265     1.00000     3.000000  970402.540800

In [9]:
cols=list(df_num.columns)
cols.remove('True_value')

In [10]:
cols

['cols_2', 'cols_5', 'cols_8', 'cols_9', 'cols_10', 'cols_11', 'cols_12']

In [11]:
for col in cols:
    median = df[col].median()
    df[col]=df[col].fillna(median)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   cols_1      6000 non-null   float64
 1   cols_2      6000 non-null   float64
 2   cols_3      6000 non-null   float64
 3   cols_4      6000 non-null   float64
 4   cols_5      6000 non-null   float64
 5   cols_6      6000 non-null   float64
 6   cols_7      6000 non-null   float64
 7   cols_8      6000 non-null   float64
 8   cols_9      6000 non-null   float64
 9   cols_10     6000 non-null   float64
 10  cols_11     6000 non-null   float64
 11  cols_12     6000 non-null   float64
 12  cols_13     6000 non-null   float64
 13  cols_14     6000 non-null   float64
 14  True_value  6000 non-null   float64
dtypes: float64(15)
memory usage: 703.3 KB


In [13]:
corr_matrix=df.corr()
corr_matrix['True_value'].sort_values(ascending=False)

True_value    1.000000
cols_2        0.514454
cols_5        0.270213
cols_10       0.238032
cols_6        0.237874
cols_3        0.223622
cols_7        0.173305
cols_11       0.103426
cols_4        0.098090
cols_12       0.096168
cols_8        0.019128
cols_14       0.012397
cols_13      -0.055708
cols_1       -0.276013
cols_9       -0.454224
Name: True_value, dtype: float64

In [14]:
# from pandas.plotting import scatter_matrix
# attr=["True_value","cols_2","cols_9","cols_1","cols_5"]
# scatter_matrix(df[attr],figsize=(12,8))

In [15]:
# df.plot(kind="scatter", x="cols_9",y="True_value", alpha=0.8)

In [16]:
corr_matrix=df.corr()
corr_matrix['True_value'].sort_values(ascending=False)

True_value    1.000000
cols_2        0.514454
cols_5        0.270213
cols_10       0.238032
cols_6        0.237874
cols_3        0.223622
cols_7        0.173305
cols_11       0.103426
cols_4        0.098090
cols_12       0.096168
cols_8        0.019128
cols_14       0.012397
cols_13      -0.055708
cols_1       -0.276013
cols_9       -0.454224
Name: True_value, dtype: float64

In [17]:
# df.info()

In [18]:
df_lables=df['True_value']
df_lables=df_lables.round()

In [19]:
# df

In [20]:
new_df=df.drop(["True_value"],axis='columns')

In [21]:
new_df['cols_4'].value_counts()

1.0    5275
0.0     725
Name: cols_4, dtype: int64

In [22]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
imputer.fit(new_df)

SimpleImputer(strategy='median')

In [23]:
imputer.statistics_

array([ 4.00000000e+00,  9.40000000e+00,  0.00000000e+00,  1.00000000e+00,
        8.51000000e+00,  1.00000000e+00,  1.00000000e+00,  1.84800000e+01,
        9.45570000e+04,  1.42857143e+00, -2.78280000e+01,  4.08882717e+00,
        0.00000000e+00,  2.00000000e+00])

In [24]:
X = imputer.transform(new_df)

In [25]:
df_tr = pd.DataFrame(X, columns=new_df.columns)

In [26]:
df_tr.describe()

cols_1       cols_2       cols_3       cols_4       cols_5  \
count  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   
mean      4.238333     9.199533     0.026667     0.879167     8.968553   
std       2.692905     0.930468     0.161121     0.325961     2.975772   
min       0.000000     2.800000     0.000000     0.000000     0.000000   
25%       1.000000     8.800000     0.000000     1.000000     7.400000   
50%       4.000000     9.400000     0.000000     1.000000     8.510000   
75%       6.000000     9.800000     0.000000     1.000000    10.360000   
max       9.000000    10.600000     1.000000     1.000000    22.940000   

            cols_6       cols_7       cols_8         cols_9      cols_10  \
count  6000.000000  6000.000000  6000.000000    6000.000000  6000.000000   
mean      1.403000     1.270333    18.648440  108785.923333     1.556905   
std       0.956771     0.755876     4.874533   74466.598693     0.344916   
min       0.000000     0.000000     0.000000       2.000000     0.000000   
25%       1.000000     1.000000    16.560000   55982.250000     1.428571   
50%       1.000000     1.000000    18.480000   94557.000000     1.428571   
75%       2.000000     2.000000    20.640000  148890.000000     1.428571   
max       3.000000     7.000000    45.840000  526162.000000     2.857143   

           cols_11      cols_12     cols_13      cols_14  
count  6000.000000  6000.000000  6000.00000  6000.000000  
mean    -28.007722     4.182368     0.42050     1.558500  
std       4.524207     0.806023     0.49368     1.061963  
min     -34.785000     1.834008     0.00000     0.000000  
25%     -27.828000     4.088827     0.00000     1.000000  
50%     -27.828000     4.088827     0.00000     2.000000  
75%     -27.828000     4.088827     1.00000     2.000000  
max     -13.914000    14.949265     1.00000     3.000000

### Creating the pipeline

In [27]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    ('std_scaler', StandardScaler()),
])

In [28]:
df_num_tr = my_pipeline.fit_transform(new_df)
df_num_tr

array([[-0.08851154,  1.07531911, -0.16552118, ..., -0.11606145,
        -0.85183657,  1.35750488],
       [-0.45988863,  0.6453921 , -0.16552118, ..., -0.11606145,
         1.17393411,  1.35750488],
       [-0.08851154, -0.21446192, -0.16552118, ..., -0.11606145,
         1.17393411, -0.52595662],
       ...,
       [-0.45988863, -0.42942543, -0.16552118, ..., -0.11606145,
        -0.85183657,  0.41577413],
       [-0.08851154, -0.85935244, -0.16552118, ..., -1.01591428,
         1.17393411,  0.41577413],
       [ 1.39699681,  0.6453921 , -0.16552118, ...,  1.62071241,
        -0.85183657,  0.41577413]])

In [29]:
df_num_tr.shape

(6000, 14)

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [88]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
    # Add other hyperparameters you want to tune
}
grid_search = GridSearchCV(RandomForestRegressor(), param_grid, cv=5, scoring='neg_mean_absolute_error', n_jobs=-1)

grid_search.fit(df_num_tr, df_lables)
best_params = grid_search.best_params_

In [89]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Ridge, Lasso
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor


estimators = [
    ('rf', LinearRegression()),
    ('svr', SVR()),
    ('dt', DecisionTreeRegressor()),
    ('knn', KNeighborsRegressor()),
    ('xgb',XGBRegressor(**best_params) ),
]

In [90]:
# model = RandomForestRegressor()
# model=DecisionTreeRegressor()
# model = LinearRegression()
model = StackingRegressor(estimators=estimators, final_estimator=RandomForestRegressor(**best_params))

In [91]:
model.fit(df_num_tr, df_lables)

D:\python\Lib\site-packages\xgboost\core.py:160: UserWarning: [17:44:30] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  warnings.warn(smsg, UserWarning)
D:\python\Lib\site-packages\xgboost\core.py:160: UserWarning: [17:44:46] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  warnings.warn(smsg, UserWarning)
D:\python\Lib\site-packages\xgboost\core.py:160: UserWarning: [17:44:51] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  warnings.warn(smsg, UserWarning)
D:\python\Lib\site-packages\

StackingRegressor(estimators=[('rf', LinearRegression()), ('svr', SVR()),
                              ('dt', DecisionTreeRegressor()),
                              ('knn', KNeighborsRegressor()),
                              ('xgb',
                               XGBRegressor(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric=None,
                                            feature...
                                            learning_rate=None, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=20,
                                            max_leaves=None,
                                            min_child_weight=None,
                                            min_samples_leaf=1,
                                            min_samples_split=2, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=300, n_jobs=None, ...))],
                  final_estimator=RandomForestRegressor(max_depth=20,
                                                        n_estimators=300))

In [92]:
some_data = new_df.iloc[:5]

In [93]:
some_labels = df_lables.iloc[:5]

In [94]:
prepared_data = my_pipeline.transform(some_data)

In [95]:
model.predict(prepared_data)

array([110202.38041071, 132738.40997171,  56875.12375356, 242634.97657323,
        85734.61068679])

In [96]:
some_labels

0    113094.0
1    125633.0
2     62801.0
3    244715.0
4     81647.0
Name: True_value, dtype: float64

### Evaluating the model

In [97]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
df_predictions = model.predict(df_num_tr)
mse = mean_squared_error(df_lables, df_predictions)
mae=mean_absolute_error(df_lables, df_predictions)
rmse = np.sqrt(mse)
mae

6375.165572993294

In [98]:
rmse

13241.228074486646

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, df_num_tr, df_lables, scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)

D:\python\Lib\site-packages\xgboost\core.py:160: UserWarning: [17:45:32] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  warnings.warn(smsg, UserWarning)
D:\python\Lib\site-packages\xgboost\core.py:160: UserWarning: [17:45:47] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  warnings.warn(smsg, UserWarning)
D:\python\Lib\site-packages\xgboost\core.py:160: UserWarning: [17:45:52] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  warnings.warn(smsg, UserWarning)
D:\python\Lib\site-packages\

In [67]:
rmse_scores

array([58755.05672699, 34284.93981804, 39072.54738643, 42530.69844818,
       39102.12829399, 42073.58826052, 39071.27716868, 40285.32421033,
       41641.36379661, 39450.87191656])

In [68]:
def print_scores(scores):
    print("Scores:", scores)
    print("Mean: ", scores.mean())
    print("Standard deviation: ", scores.std())

In [69]:
print_scores(rmse_scores)

Scores: [58755.05672699 34284.93981804 39072.54738643 42530.69844818
 39102.12829399 42073.58826052 39071.27716868 40285.32421033
 41641.36379661 39450.87191656]
Mean:  41626.77960263317
Standard deviation:  6117.679662980459


### Final Prediction

In [ ]:
from joblib import dump, load
dump(model, 'Ankit.joblib')